"""Versioned strict interchange contract; generated from the reviewed draft schema."""

SCHEMA = {'$schema': 'http://json-schema.org/draft-07/schema#',
 'title': 'Bunki maintenance intake draft v1',
 'description': 'Report and proposal interchange only. Server validates actor, evidence references and '
                'authority independently; no execution capability is conferred.',
 'oneOf': [{'$ref': '#/definitions/LearnerReport'}, {'$ref': '#/definitions/BuildProposal'}],
 'definitions': {'LearnerReport': {'type': 'object',
                                   'additionalProperties': False,
                                   'properties': {'schema_version': {'const': 'bunki.maintenance/v1'},
                                                  'id': {'type': 'string',
                                                         'pattern': '^[a-z][a-z0-9_-]{2,95}$'},
                                                  'revision': {'type': 'integer', 'minimum': 1},
                                                  'created_at': {'type': 'string', 'format': 'date-time'},
                                                  'origin': {'type': 'object',
                                                             'additionalProperties': False,
                                                             'properties': {'kind': {'const': 'user'},
                                                                            'actor_ref': {'type': 'string',
                                                                                          'minLength': 1,
                                                                                          'maxLength': 160},
                                                                            'model_ref': {'type': ['string',
                                                                                                   'null'],
                                                                                          'maxLength': 200}},
                                                             'required': ['kind', 'actor_ref', 'model_ref']},
                                                  'context': {'type': 'object',
                                                              'additionalProperties': False,
                                                              'properties': {'app_id': {'const': 'bunki'},
                                                                             'surface': {'type': 'string',
                                                                                         'minLength': 1,
                                                                                         'maxLength': 160},
                                                                             'route': {'type': 'string',
                                                                                       'minLength': 1,
                                                                                       'maxLength': 500},
                                                                             'build': {'type': 'object',
                                                                                       'additionalProperties': False,
                                                                                       'properties': {'git_sha': {'type': ['string',
                                                                                                                           'null'],
                                                                                                                  'pattern': '^[a-f0-9]{40}$'},
                                                                                                      'artifact_sha256': {'type': ['string',
                                                                                                                                   'null'],
                                                                                                                          'pattern': '^[a-f0-9]{64}$'}},
                                                                                       'required': ['git_sha',
                                                                                                    'artifact_sha256']},
                                                                             'content_ids': {'type': 'array',
                                                                                             'items': {'type': 'string',
                                                                                                       'minLength': 1,
                                                                                                       'maxLength': 160},
                                                                                             'minItems': 0,
                                                                                             'maxItems': 32},
                                                                             'locale': {'type': 'string',
                                                                                        'minLength': 1,
                                                                                        'maxLength': 32}},
                                                              'required': ['app_id',
                                                                           'surface',
                                                                           'route',
                                                                           'build',
                                                                           'content_ids',
                                                                           'locale']},
                                                  'evidence': {'type': 'array',
                                                               'items': {'type': 'object',
                                                                         'additionalProperties': False,
                                                                         'properties': {'id': {'type': 'string',
                                                                                               'pattern': '^[a-z][a-z0-9_-]{2,95}$'},
                                                                                        'kind': {'enum': ['user_quote',
                                                                                                          'screenshot',
                                                                                                          'action_trace',
                                                                                                          'source_inspection',
                                                                                                          'test_receipt']},
                                                                                        'summary': {'type': 'string',
                                                                                                    'minLength': 1,
                                                                                                    'maxLength': 4000},
                                                                                        'artifact_ref': {'type': ['string',
                                                                                                                  'null'],
                                                                                                         'maxLength': 200}},
                                                                         'required': ['id',
                                                                                      'kind',
                                                                                      'summary',
                                                                                      'artifact_ref']},
                                                               'minItems': 1,
                                                               'maxItems': 32},
                                                  'execution_authority': {'const': 'none'},
                                                  'kind': {'const': 'learner_report'},
                                                  'category': {'enum': ['bug',
                                                                        'content',
                                                                        'experience',
                                                                        'idea']},
                                                  'user_words': {'type': 'string',
                                                                 'minLength': 1,
                                                                 'maxLength': 12000},
                                                  'expected': {'type': 'string',
                                                               'minLength': 1,
                                                               'maxLength': 4000},
                                                  'actual': {'type': 'string',
                                                             'minLength': 1,
                                                             'maxLength': 4000},
                                                  'reproduction_steps': {'type': 'array',
                                                                         'items': {'type': 'string',
                                                                                   'minLength': 1,
                                                                                   'maxLength': 1000},
                                                                         'minItems': 0,
                                                                         'maxItems': 20},
                                                  'attachment_ids': {'type': 'array',
                                                                     'items': {'type': 'string',
                                                                               'pattern': '^[a-z][a-z0-9_-]{2,95}$'},
                                                                     'minItems': 0,
                                                                     'maxItems': 8}},
                                   'required': ['schema_version',
                                                'id',
                                                'revision',
                                                'created_at',
                                                'origin',
                                                'context',
                                                'evidence',
                                                'execution_authority',
                                                'kind',
                                                'category',
                                                'user_words',
                                                'expected',
                                                'actual',
                                                'reproduction_steps',
                                                'attachment_ids']},
                 'BuildProposal': {'type': 'object',
                                   'additionalProperties': False,
                                   'properties': {'schema_version': {'const': 'bunki.maintenance/v1'},
                                                  'id': {'type': 'string',
                                                         'pattern': '^[a-z][a-z0-9_-]{2,95}$'},
                                                  'revision': {'type': 'integer', 'minimum': 1},
                                                  'created_at': {'type': 'string', 'format': 'date-time'},
                                                  'origin': {'type': 'object',
                                                             'additionalProperties': False,
                                                             'properties': {'kind': {'const': 'sensei'},
                                                                            'actor_ref': {'type': 'string',
                                                                                          'minLength': 1,
                                                                                          'maxLength': 160},
                                                                            'model_ref': {'type': ['string',
                                                                                                   'null'],
                                                                                          'maxLength': 200}},
                                                             'required': ['kind', 'actor_ref', 'model_ref']},
                                                  'context': {'type': 'object',
                                                              'additionalProperties': False,
                                                              'properties': {'app_id': {'const': 'bunki'},
                                                                             'surface': {'type': 'string',
                                                                                         'minLength': 1,
                                                                                         'maxLength': 160},
                                                                             'route': {'type': 'string',
                                                                                       'minLength': 1,
                                                                                       'maxLength': 500},
                                                                             'build': {'type': 'object',
                                                                                       'additionalProperties': False,
                                                                                       'properties': {'git_sha': {'type': ['string',
                                                                                                                           'null'],
                                                                                                                  'pattern': '^[a-f0-9]{40}$'},
                                                                                                      'artifact_sha256': {'type': ['string',
                                                                                                                                   'null'],
                                                                                                                          'pattern': '^[a-f0-9]{64}$'}},
                                                                                       'required': ['git_sha',
                                                                                                    'artifact_sha256']},
                                                                             'content_ids': {'type': 'array',
                                                                                             'items': {'type': 'string',
                                                                                                       'minLength': 1,
                                                                                                       'maxLength': 160},
                                                                                             'minItems': 0,
                                                                                             'maxItems': 32},
                                                                             'locale': {'type': 'string',
                                                                                        'minLength': 1,
                                                                                        'maxLength': 32}},
                                                              'required': ['app_id',
                                                                           'surface',
                                                                           'route',
                                                                           'build',
                                                                           'content_ids',
                                                                           'locale']},
                                                  'evidence': {'type': 'array',
                                                               'items': {'type': 'object',
                                                                         'additionalProperties': False,
                                                                         'properties': {'id': {'type': 'string',
                                                                                               'pattern': '^[a-z][a-z0-9_-]{2,95}$'},
                                                                                        'kind': {'enum': ['user_quote',
                                                                                                          'screenshot',
                                                                                                          'action_trace',
                                                                                                          'source_inspection',
                                                                                                          'test_receipt']},
                                                                                        'summary': {'type': 'string',
                                                                                                    'minLength': 1,
                                                                                                    'maxLength': 4000},
                                                                                        'artifact_ref': {'type': ['string',
                                                                                                                  'null'],
                                                                                                         'maxLength': 200}},
                                                                         'required': ['id',
                                                                                      'kind',
                                                                                      'summary',
                                                                                      'artifact_ref']},
                                                               'minItems': 1,
                                                               'maxItems': 32},
                                                  'execution_authority': {'const': 'none'},
                                                  'kind': {'const': 'build_proposal'},
                                                  'source_report_ids': {'type': 'array',
                                                                        'items': {'type': 'string',
                                                                                  'pattern': '^[a-z][a-z0-9_-]{2,95}$'},
                                                                        'minItems': 0,
                                                                        'maxItems': 32},
                                                  'title': {'type': 'string',
                                                            'minLength': 1,
                                                            'maxLength': 180},
                                                  'problem': {'type': 'string',
                                                              'minLength': 1,
                                                              'maxLength': 4000},
                                                  'claims': {'type': 'array',
                                                             'items': {'type': 'object',
                                                                       'additionalProperties': False,
                                                                       'properties': {'text': {'type': 'string',
                                                                                               'minLength': 1,
                                                                                               'maxLength': 4000},
                                                                                      'basis': {'enum': ['user_report',
                                                                                                         'inspection',
                                                                                                         'hypothesis']},
                                                                                      'evidence_ids': {'type': 'array',
                                                                                                       'items': {'type': 'string',
                                                                                                                 'pattern': '^[a-z][a-z0-9_-]{2,95}$'},
                                                                                                       'minItems': 1,
                                                                                                       'maxItems': 16}},
                                                                       'required': ['text',
                                                                                    'basis',
                                                                                    'evidence_ids']},
                                                             'minItems': 1,
                                                             'maxItems': 32},
                                                  'proposed_change': {'type': 'string',
                                                                      'minLength': 1,
                                                                      'maxLength': 12000},
                                                  'proposed_files': {'type': 'array',
                                                                     'items': {'type': 'string',
                                                                               'minLength': 1,
                                                                               'maxLength': 500},
                                                                     'minItems': 0,
                                                                     'maxItems': 64},
                                                  'acceptance_cases': {'type': 'array',
                                                                       'items': {'type': 'object',
                                                                                 'additionalProperties': False,
                                                                                 'properties': {'id': {'type': 'string',
                                                                                                       'pattern': '^[a-z][a-z0-9_-]{2,95}$'},
                                                                                                'given': {'type': 'string',
                                                                                                          'minLength': 1,
                                                                                                          'maxLength': 2000},
                                                                                                'when': {'type': 'string',
                                                                                                         'minLength': 1,
                                                                                                         'maxLength': 2000},
                                                                                                'then': {'type': 'string',
                                                                                                         'minLength': 1,
                                                                                                         'maxLength': 3000}},
                                                                                 'required': ['id',
                                                                                              'given',
                                                                                              'when',
                                                                                              'then']},
                                                                       'minItems': 1,
                                                                       'maxItems': 32},
                                                  'unknowns': {'type': 'array',
                                                               'items': {'type': 'string',
                                                                         'minLength': 1,
                                                                         'maxLength': 2000},
                                                               'minItems': 0,
                                                               'maxItems': 32},
                                                  'rollback': {'type': 'string',
                                                               'minLength': 1,
                                                               'maxLength': 4000},
                                                  'requested_action': {'const': 'review'}},
                                   'required': ['schema_version',
                                                'id',
                                                'revision',
                                                'created_at',
                                                'origin',
                                                'context',
                                                'evidence',
                                                'execution_authority',
                                                'kind',
                                                'source_report_ids',
                                                'title',
                                                'problem',
                                                'claims',
                                                'proposed_change',
                                                'proposed_files',
                                                'acceptance_cases',
                                                'unknowns',
                                                'rollback',
                                                'requested_action']}}}
