/**
 * Event construction through the injected context (WP-02).
 *
 * Two rules meet in this file.
 *
 * **Determinism (REQ-ARCH-02).** `eventId` and `occurredAt` come from the
 * `DomainContext`, never from an ambient clock or id source. That is what lets
 * a golden fixture be regenerated byte-for-byte and lets WP-03's adapters
 * replay to the same state as this in-memory reference (T-03).
 *
 * **The evidence boundary (REQ-ARCH-04).** This factory can construct only
 * non-evidence families. Evidence-class events — `ReviewGraded`,
 * `ProductionObserved`, `ExposureLogged`, `LookupFrictionLogged`,
 * `EvidenceSuperseded` — are minted exclusively by the evidence gate in
 * `src/evidence/` (WP-06), because whether an observation *counts* is the
 * gate's judgement and a generic constructor would route around it. The type
 * parameter excludes them at compile time; `EvidenceFactoryBoundaryError` is
 * the runtime backstop for a caller that arrived through `any`.
 *
 * Everything built here is validated on the way out. A factory that could emit
 * an event the parser would reject would mean two disagreeing definitions of
 * valid, and the log would inherit whichever ran first.
 */

import type { DomainContext } from '../context/index.ts';
import { EvidenceFactoryBoundaryError } from '../errors.ts';
import type { IsoInstant } from '../primitives.ts';
import {
  isEvidenceEventType,
  type DomainEventType,
  type EventOfType,
  type NonEvidenceEventType,
} from './catalog.ts';
import { EVENT_SCHEMA_VERSION } from './envelope.ts';
import { parseEvent } from './parse.ts';

/** The family-specific fields — everything the envelope and discriminator do not cover. */
export type EventPayload<TType extends DomainEventType> = Omit<
  EventOfType<TType>,
  'eventId' | 'v' | 'occurredAt' | 'idempotencyKey' | 'type'
>;

export interface CreateEventOptions {
  /**
   * Required, never defaulted.
   *
   * A generated key would make every double-tap a distinct event and quietly
   * undo the one guarantee this field exists for (§7). The caller knows what
   * makes this action the same action; the kernel does not.
   */
  readonly idempotencyKey: string;
  /** Overrides the context's id — for replaying a recorded event verbatim. */
  readonly eventId?: string;
  /** Overrides the context's clock — for backdating an imported observation. */
  readonly occurredAt?: IsoInstant;
}

/**
 * Build a validated non-evidence event.
 *
 * @throws EvidenceFactoryBoundaryError if called with an evidence-class type.
 * @throws EventValidationError if the assembled event does not satisfy its schema.
 */
export function createDomainEvent<TType extends NonEvidenceEventType>(
  context: DomainContext,
  type: TType,
  payload: EventPayload<TType>,
  options: CreateEventOptions,
): EventOfType<TType> {
  if (isEvidenceEventType(type as DomainEventType)) {
    throw new EvidenceFactoryBoundaryError(type);
  }

  const candidate = {
    ...payload,
    type,
    eventId: options.eventId ?? context.ids.nextId('event'),
    v: EVENT_SCHEMA_VERSION,
    occurredAt: options.occurredAt ?? context.clock.now(),
    idempotencyKey: options.idempotencyKey,
  };

  return parseEvent(candidate) as EventOfType<TType>;
}
