/**
 * The scripted learner, checked against the kernel it was generated by (lane L1).
 *
 * The claim this file exists to make good is a single sentence and it is the
 * whole reason the generator was allowed to exist at all:
 *
 * > The generated log is not a mock. It replays. It exports. It is exactly what
 * > a real learner would have produced, because it went through the same code.
 *
 * So the assertions below are not "the numbers look plausible". They are:
 *
 *   - **it replays to the same state.** The generator folds memory states
 *     forward as it writes, using the same reducer replay uses, so that it can
 *     ask the real gate what is due. If those two ever disagreed, the generator
 *     would be a second scheduler and the log would be describing a history the
 *     kernel does not agree with. Byte-for-byte equality of the canonical
 *     rendering is the check, because structural equality hides exactly the
 *     divergence the export round trip would then fail on.
 *   - **it is kernel-minted.** Every event is accepted by `sealMintedEvents`,
 *     which refuses anything this process's own minters did not produce
 *     unaltered. A hand-written log cannot pass this, which is the point.
 *   - **it parses.** Through `parseEventLog`, the same fail-closed parser that
 *     reads a durable log — so a fixture the parser would reject cannot hide
 *     behind having been built in memory.
 *   - **it is deterministic.** Same seed, same start day, byte-identical log.
 *   - **the four stages differ in kind.** Each stage asserts the property its
 *     brief asked for, so a re-tuning that quietly flattened the plateau, or
 *     removed the lapses, fails here rather than in a screenshot nobody
 *     re-took.
 */

import { describe, expect, it } from 'vitest';

import {
  canonicalJson,
  parseEventLog,
  replay,
  replayTwiceAndCompare,
  sealMintedEvents,
  type DomainEvent,
  type ReviewGradedEvent,
} from '../../src/index.ts';
import {
  DEMO_STAGES,
  demoStageById,
  generateScriptedLearner,
  MONTH_8,
  SCRIPTED_LEARNER_SOURCE_ID,
  YEAR_2,
  type DemoStageScript,
  type ScriptedLearnerLog,
} from '../../src/demo/index.ts';
import { epochMsOfInstant, MS_PER_DAY } from '../../src/demo/calendar.ts';
import { TEST_START_DAY, testContractIdFor, testCorpus } from './support.ts';

const run = (script: DemoStageScript, startDay: string = TEST_START_DAY): ScriptedLearnerLog =>
  generateScriptedLearner({
    script,
    corpus: testCorpus(script.corpusBudget),
    startDay,
    idPrefix: `demo-${script.id}`,
    contractIdFor: testContractIdFor,
  });

/**
 * Generated once per stage, and replayed once per stage.
 *
 * Both are memoised because both are the expensive thing this lane measures:
 * the largest stage is fifteen thousand events over nine hundred contracts, and
 * `replay` is quadratic in their product. A suite that replayed per assertion
 * would spend three minutes proving what one replay proves, and would be the
 * first thing a future lane deleted for being slow.
 */
const LOGS = new Map<string, ScriptedLearnerLog>(
  DEMO_STAGES.map((script) => [script.id, run(script)] as const),
);

const REPLAYS = new Map<string, ReturnType<typeof replay>>();

const logFor = (id: string): ScriptedLearnerLog => {
  const log = LOGS.get(id);
  if (log === undefined) throw new Error(`no generated log for stage ${id}`);
  return log;
};

const stateOf = (id: string): ReturnType<typeof replay> => {
  const cached = REPLAYS.get(id);
  if (cached !== undefined) return cached;
  const state = replay(logFor(id).events);
  REPLAYS.set(id, state);
  return state;
};

const stageCases = DEMO_STAGES.map((script) => [script.id, script] as const);

/** Room for a slow machine; the heaviest of these is a few seconds here. */
const HEAVY = 120_000;

/* ------------------------------------------------------------------ *
 * The log is a real log
 * ------------------------------------------------------------------ */

describe('every stage produces a log this kernel recognises as its own', () => {
  it.each(stageCases)('%s: every event was minted here, unaltered', (id) => {
    // `sealMintedEvents` throws unless every member is an object one of the
    // kernel's minters returned and nothing has been changed since. A
    // hand-assembled log fails this call; that is what makes passing it mean
    // something.
    expect(() => sealMintedEvents(logFor(id).events)).not.toThrow();
  });

  it.each(stageCases)('%s: survives the fail-closed parser', (id) => {
    const events = logFor(id).events;
    // Round-tripped through JSON first, so the parser sees what a durable
    // adapter would hand it rather than the in-memory objects.
    const raw: unknown = JSON.parse(JSON.stringify(events));
    expect(parseEventLog(raw, { path: `demo:${id}` })).toHaveLength(events.length);
  });

  it.each(stageCases)(
    '%s: replays to the state the generator folded forward',
    (id) => {
      const log = logFor(id);
      const state = stateOf(id);
      expect(state.appliedEventCount).toBe(log.events.length);
      expect(state.skippedDuplicateCount).toBe(0);
      expect(canonicalJson(state.memoryStates)).toBe(canonicalJson(log.memoryStates));
    },
    HEAVY,
  );

  it.each(stageCases)(
    '%s: replays twice to byte-identical state',
    (id) => {
      const result = replayTwiceAndCompare(logFor(id).events);
      expect(result.identical).toBe(true);
    },
    HEAVY,
  );

  it.each(stageCases)(
    '%s: is byte-identical on a second generation',
    (_id, script) => {
      expect(canonicalJson(run(script).events)).toBe(canonicalJson(run(script).events));
    },
    HEAVY,
  );

  it.each(stageCases)('%s: is in chronological order', (id) => {
    const events = logFor(id).events;
    for (let index = 1; index < events.length; index += 1) {
      const previous = events[index - 1];
      const current = events[index];
      if (previous === undefined || current === undefined) continue;
      expect(
        current.occurredAt >= previous.occurredAt,
        `event ${String(index)} (${current.type}) goes backwards in time`,
      ).toBe(true);
    }
  });

  it.each(stageCases)('%s: stays inside the days its script declares', (id, script) => {
    const log = logFor(id);
    const first = epochMsOfInstant(log.startedAt);
    const last = epochMsOfInstant(log.endedAt);
    expect(last).toBeGreaterThanOrEqual(first);
    expect(last - first).toBeLessThan(script.days * MS_PER_DAY);
  });

  it.each(stageCases)('%s: labels itself as a demonstration on every encounter', (id) => {
    const captures = logFor(id).events.filter((event) => event.type === 'EncounterCaptured');
    expect(captures.length).toBeGreaterThan(0);
    for (const capture of captures) {
      if (capture.type !== 'EncounterCaptured') continue;
      expect(capture.sourceRef.sourceId).toBe(SCRIPTED_LEARNER_SOURCE_ID);
      expect(capture.provenance.source).toBe(SCRIPTED_LEARNER_SOURCE_ID);
      expect(capture.provenance.attribution).toMatch(/does not exist/);
    }
  });

  it('is a different log for a different start day', () => {
    const early = run(MONTH_8, '2024-01-01T00:00:00.000Z');
    const late = run(MONTH_8, '2025-03-04T00:00:00.000Z');
    expect(early.events.length).toBe(late.events.length);
    expect(canonicalJson(early.events)).not.toBe(canonicalJson(late.events));
  });
});

/* ------------------------------------------------------------------ *
 * The gate is the sole judge, and it said no where it had to
 * ------------------------------------------------------------------ */

describe('what the evidence gate did with the scripted observations', () => {
  it.each(stageCases)('%s: no exposure ever reached the scheduler (T-08)', (id) => {
    const decisions = stateOf(id).gateDecisions.filter(
      (decision) => decision.type === 'ExposureLogged',
    );
    for (const decision of decisions) {
      expect(decision.admitted).toBe(false);
      expect(decision.reason).toBe('exposure_is_never_retrieval');
    }
  });

  it.each(stageCases)('%s: no lookup ever became a grade (T-07)', (id) => {
    for (const decision of stateOf(id).gateDecisions) {
      if (decision.type !== 'LookupFrictionLogged') continue;
      expect(decision.admitted).toBe(false);
      expect(decision.effectiveGrade).toBeNull();
    }
  });

  it.each(stageCases)('%s: no production observation reached FSRS (REQ-DM-06)', (id) => {
    for (const decision of stateOf(id).gateDecisions) {
      if (decision.type !== 'ProductionObserved') continue;
      expect(decision.admitted).toBe(false);
      expect(decision.reason).toBe('production_is_not_tier_a');
    }
  });

  it.each(stageCases)('%s: every reveal was recorded as an again (T-06)', (id) => {
    const revealed = logFor(id).events.filter(
      (event): event is ReviewGradedEvent =>
        event.type === 'ReviewGraded' && event.revealedBeforeRecall,
    );
    for (const event of revealed) expect(event.grade).toBe('again');
  });

  it('records a refusal with a named reason on the larger stages', () => {
    // The ledger has to be able to answer "why did that one not count", which
    // it cannot do if nothing was ever refused. Not asserted on day 3, where a
    // learner with eleven reviews legitimately may have had none.
    for (const id of ['month-2', 'month-8', 'year-2']) {
      const summary = logFor(id).summary;
      expect(summary.refusedReviewCount, id).toBeGreaterThan(0);
      expect(Object.keys(summary.refusalsByReason).length, id).toBeGreaterThan(0);
      for (const reason of Object.keys(summary.refusalsByReason)) {
        expect(reason).not.toBe('');
      }
    }
  });

  it('corrects observations by appending, never by rewriting (REQ-DM-04.2)', () => {
    const log = logFor('year-2');
    const state = stateOf('year-2');
    const corrections = log.events.filter((event) => event.type === 'EvidenceSuperseded');
    expect(corrections.length).toBeGreaterThan(0);

    for (const correction of corrections) {
      if (correction.type !== 'EvidenceSuperseded') continue;
      // The original is still in the ledger, marked rather than removed…
      const original = state.observations.find(
        (observation) => observation.eventId === correction.supersededEventId,
      );
      expect(original, 'the corrected observation left the ledger').toBeDefined();
      expect(original?.superseded).toBe(true);
      expect(original?.supersededByEventId).toBe(correction.eventId);
      // …and the gate kept it out of the scheduler.
      const decision = state.gateDecisions.find(
        (entry) => entry.eventId === correction.supersededEventId,
      );
      expect(decision?.admitted).toBe(false);
      expect(decision?.reason).toBe('evidence_superseded');
    }
  });
});

/* ------------------------------------------------------------------ *
 * The four stages differ in kind
 * ------------------------------------------------------------------ */

describe('day 3 is a learner three days in', () => {
  const log = () => logFor('day-3');

  it('has a handful of threads and no long interval anywhere', () => {
    const summary = log().summary;
    expect(summary.threadCount).toBeLessThanOrEqual(15);
    expect(summary.contractCount).toBeLessThanOrEqual(20);
    for (const state of log().memoryStates) {
      // Nothing has settled: the largest interval a three-day-old contract can
      // hold is a few days, and certainly not a month.
      expect(state.scheduledDays).toBeLessThan(30);
    }
  });

  it('has sat at least one sitting, and closed it explicitly', () => {
    const sessions = stateOf('day-3').sessions;
    expect(sessions.length).toBeGreaterThan(0);
    for (const session of sessions) {
      expect(session.status).toBe('closed');
      expect(session.completionState).not.toBeNull();
    }
  });
});

describe('month 2 is a habit with its first cracks', () => {
  const log = () => logFor('month-2');

  it('holds a few hundred contracts', () => {
    expect(log().summary.contractCount).toBeGreaterThanOrEqual(200);
    expect(log().summary.contractCount).toBeLessThan(600);
  });

  it('has lapsed, left a sitting, and marked things uncertain', () => {
    const summary = log().summary;
    expect(summary.lapseCount).toBeGreaterThan(0);
    expect(summary.sessionCounts.abandoned).toBeGreaterThan(0);
    expect(summary.uncertaintyMarkCount).toBeGreaterThan(0);
  });

  it('has at least one fragile contract — recently lapsed, short interval', () => {
    const fragile = log().memoryStates.filter(
      (state) => state.lapses > 0 && state.stability < 7 && state.active,
    );
    expect(fragile.length).toBeGreaterThan(0);
  });

  it('reads well ahead of what it can produce', () => {
    const bySkill = log().summary.contractsBySkill;
    expect(bySkill.orthography_to_reading ?? 0).toBeGreaterThan(
      (bySkill.meaning_to_production ?? 0) * 10,
    );
  });
});

describe('month 8 is a plateau, and it is a plateau in the data', () => {
  const log = () => logFor('month-8');

  it('stopped taking anything new in the last third', () => {
    const events = log().events;
    const start = epochMsOfInstant(log().startedAt);
    const plateauFrom = start + 130 * MS_PER_DAY;
    const capturedInPlateau = events.filter(
      (event) =>
        event.type === 'EncounterCaptured' && epochMsOfInstant(event.occurredAt) >= plateauFrom,
    ).length;
    const capturedBefore = events.filter(
      (event) =>
        event.type === 'EncounterCaptured' && epochMsOfInstant(event.occurredAt) < plateauFrom,
    ).length;
    // Intake did not merely slow: it all but stopped, while the sittings went on.
    expect(capturedInPlateau * 8).toBeLessThan(capturedBefore);
  });

  it('kept reviewing throughout, and found it easy', () => {
    const events = log().events;
    const plateauFrom = epochMsOfInstant(log().startedAt) + 130 * MS_PER_DAY;
    const late = events.filter(
      (event): event is ReviewGradedEvent =>
        event.type === 'ReviewGraded' && epochMsOfInstant(event.occurredAt) >= plateauFrom,
    );
    expect(late.length).toBeGreaterThan(100);
    const easy = late.filter((event) => event.grade === 'easy').length;
    const again = late.filter((event) => event.grade === 'again').length;
    expect(easy / late.length).toBeGreaterThan(0.35);
    expect(again / late.length).toBeLessThan(0.05);
  });

  it('has capability lenses that are four different pictures', () => {
    const bySkill = log().summary.contractsBySkill;
    const reading = bySkill.orthography_to_reading ?? 0;
    const meaning = bySkill.form_to_meaning ?? 0;
    const listening = bySkill.audio_to_meaning ?? 0;
    const production = bySkill.meaning_to_production ?? 0;
    expect(reading).toBeGreaterThan(meaning);
    expect(meaning).toBeGreaterThan(listening);
    expect(listening).toBeGreaterThan(production);
    // Writing has no contract skill in this build at all, which is the fifth
    // lens and stays `unknown` — the honest answer, not a gap this fills in.
    expect(Object.keys(bySkill)).not.toContain('writing');
  });

  it('has the plateau declared in the script a reader can check', () => {
    const last = MONTH_8.phases[MONTH_8.phases.length - 1];
    expect(last?.name).toBe('the plateau');
    expect(last?.gradeMix.again).toBe(0);
    expect(last?.captureDayChance).toBeLessThan(0.1);
  });
});

describe('year 2 is deep, uneven, and has a gap in the middle', () => {
  const log = () => logFor('year-2');

  it('has a long tail met once and never promoted', () => {
    const summary = log().summary;
    expect(summary.metOnceCount).toBeGreaterThan(200);
    expect(summary.metOnceCount / summary.threadCount).toBeGreaterThan(0.25);
  });

  it('has corrections in the ledger', () => {
    expect(log().summary.correctionCount).toBeGreaterThan(10);
  });

  it('has branch points the journey surface can open on', () => {
    // A branch opens on an admitted review the gate reveal-corrected to `again`
    // — the ledger's own definition, read back off the ledger.
    const lapses = stateOf('year-2').gateDecisions.filter(
      (decision) => decision.admitted && decision.effectiveGrade === 'again',
    );
    expect(lapses.length).toBeGreaterThan(50);
  });

  it('went quiet for three months and came back to a wall', () => {
    const events = log().events;
    const start = epochMsOfInstant(log().startedAt);
    const dayOf = (event: DomainEvent): number =>
      Math.floor((epochMsOfInstant(event.occurredAt) - start) / MS_PER_DAY);

    const reviewsIn = (from: number, to: number): number =>
      events.filter((event) => {
        if (event.type !== 'ReviewGraded') return false;
        const day = dayOf(event);
        return day >= from && day < to;
      }).length;

    const away = reviewsIn(310, 390);
    const before = reviewsIn(220, 300);
    const back = reviewsIn(395, 470);
    expect(away * 5).toBeLessThan(before);
    expect(back).toBeGreaterThan(away * 5);
  });

  it('shows real decay: a backlog at the end, and items that lapsed more than once', () => {
    // Two different facts, both the pinned model's rather than this module's.
    //
    // The backlog is what a learner who reviews four or five days a week over
    // two years actually has: a queue that is never empty, which is why the
    // sittings end `budget_exhausted` more often than `completed`.
    const end = epochMsOfInstant(log().endedAt);
    const backlog = log().memoryStates.filter(
      (state) => state.active && epochMsOfInstant(state.dueAt) <= end,
    );
    expect(backlog.length).toBeGreaterThan(20);

    // And the repeat lapses are the unevenness: contracts this learner has
    // forgotten more than once, which is where the fragile marks come from.
    const repeatedlyLapsed = log().memoryStates.filter((state) => state.lapses >= 2);
    expect(repeatedlyLapsed.length).toBeGreaterThan(20);
  });

  it('names its own hiatus in the script', () => {
    expect(YEAR_2.phases.map((entry) => entry.name)).toContain('three months away');
  });
});

/* ------------------------------------------------------------------ *
 * Cost, reported rather than assumed
 * ------------------------------------------------------------------ */

describe('the cost of opening a stage', () => {
  it('reports a replay-cost hint that matches the log it describes', () => {
    for (const script of DEMO_STAGES) {
      const log = logFor(script.id);
      expect(log.summary.replayCostHint).toBe(log.summary.eventCount * log.summary.contractCount);
    }
  });

  /**
   * A ceiling, not a benchmark.
   *
   * Replay is quadratic in (events × contracts) — see `generate.ts` §cost — so
   * the largest stage is the one that decides whether loading a demonstration
   * feels like a build or like a hang. The number below is roughly three times
   * what this container measures, which leaves room for a slower machine while
   * still failing if a re-tuning doubled the stage.
   */
  it('keeps the largest stage under a stated ceiling', () => {
    expect(logFor('year-2').summary.replayCostHint).toBeLessThan(25_000_000);
  });

  it('finds every declared stage by id, and no others', () => {
    for (const script of DEMO_STAGES) expect(demoStageById(script.id)).toBe(script);
    expect(demoStageById('month-3')).toBeNull();
  });
});
